version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc/casc.yaml
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/casc.yaml:/var/jenkins_home/casc/casc.yaml
      - ./pipelines:/var/jenkins_home/pipelines
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home:
